package tui

// Code generated by assets/gen_logo.py. DO NOT EDIT.

// bannerInk and bannerGreen are the two halves of the CLIOne wordmark drawn
// with half-block characters: bannerInk holds the prompt and "CLI",
// bannerGreen the "One". They are rendered side by side, one line at a time,
// so each half can carry its own color -- see renderBanner in app.go.
var (
	bannerInk = []string{
		"▀█▄        ▄▀▀▀▄ █     ▀▀█▀▀ ",
		"  ▀█▄      █     █       █   ",
		" ▄█▀       █   ▄ █       █   ",
		"▀▀          ▀▀▀  ▀▀▀▀▀ ▀▀▀▀▀ ",
		"   ▀▀▀▀▀",
	}

	bannerGreen = []string{
		"▄▀▀▀▄",
		"█   █ █▄▀▀▄ ▄▀▀▀▄",
		"█   █ █   █ █▀▀▀▀",
		" ▀▀▀  ▀   ▀  ▀▀▀",
		"",
	}
)

// bannerWidth is the column width of the widest banner line, used to decide
// whether the terminal is wide enough to show the wordmark at all.
const bannerWidth = 46
